# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.CharField(max_length=20)),
                ('productName', models.CharField(max_length=100)),
                ('productDesc', models.CharField(max_length=500)),
                ('productStock', models.IntegerField(max_length=10)),
            ],
        ),
    ]
